controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute



app_task_view:
    path: '/task/view/{id}'
    controller: App\Controller\TaskController::view


task_delete:
    path: /task/list
    controller: App\Controller\TaskController::delete
    methods: ['POST']

task_update:
    path: '/task/update/{id}'
    controller: App\Controller\TaskController::update

task_create:
    path: '/task/create'
    controller: App\Controller\TaskController::create
    
    # list:
    # path: '/task/list'
    # controller: App\Controller\TaskController::list